stack:
  name: terragrunt-options-test
  backend: terraform
  working_directory: .
  triggers:
    - terragrunt.hcl
  terraform_provider:
    command: terragrunt
  before_init:
    - terragrunt --terragrunt-log-level debug
